version: 2

jobs:
  build:
    machine:
      image: windows-default
    resource_class: windows.large
    parallelism: 8
    steps:
     - checkout
     - run: |
          pip install pytest-playwright
          playwright install
          pytest up.py
