version: 2.1
orbs:
  win: circleci/windows@4.1
jobs:
  build:
    executor: 
      name: win/server-2019
      size: large
    parallelism: 8
    steps:
     - checkout
     - run: |
          pip install pytest-playwright
          playwright install
          pytest up.py
          
workflows:
  my-workflow:
    jobs:
      - build
