version: 2.1
orbs:
  win: circleci/windows@4.1
jobs:
  build:
    executor: 
      name: win/server-2019
      size: large
    parallelism: 8
    steps:
     - checkout
     - run: |
          docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome
          pip install selenium
          python sel.py
          
workflows:
  my-workflow:
    jobs:
      - build
